//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Images = newImagesTable("public", "images", "")

type imagesTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	ImageLink postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ImagesTable struct {
	imagesTable

	EXCLUDED imagesTable
}

// AS creates new ImagesTable with assigned alias
func (a ImagesTable) AS(alias string) *ImagesTable {
	return newImagesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ImagesTable with assigned schema name
func (a ImagesTable) FromSchema(schemaName string) *ImagesTable {
	return newImagesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ImagesTable with assigned table prefix
func (a ImagesTable) WithPrefix(prefix string) *ImagesTable {
	return newImagesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ImagesTable with assigned table suffix
func (a ImagesTable) WithSuffix(suffix string) *ImagesTable {
	return newImagesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newImagesTable(schemaName, tableName, alias string) *ImagesTable {
	return &ImagesTable{
		imagesTable: newImagesTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newImagesTableImpl("", "excluded", ""),
	}
}

func newImagesTableImpl(schemaName, tableName, alias string) imagesTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		ImageLinkColumn = postgres.StringColumn("image_link")
		allColumns      = postgres.ColumnList{IDColumn, ImageLinkColumn}
		mutableColumns  = postgres.ColumnList{ImageLinkColumn}
	)

	return imagesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		ImageLink: ImageLinkColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
