//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Users = newUsersTable("public", "users", "")

type usersTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnInteger
	FirstName   postgres.ColumnString
	LastName    postgres.ColumnString
	Email       postgres.ColumnString
	Address     postgres.ColumnString
	PhoneNumber postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type UsersTable struct {
	usersTable

	EXCLUDED usersTable
}

// AS creates new UsersTable with assigned alias
func (a UsersTable) AS(alias string) *UsersTable {
	return newUsersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UsersTable with assigned schema name
func (a UsersTable) FromSchema(schemaName string) *UsersTable {
	return newUsersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UsersTable with assigned table prefix
func (a UsersTable) WithPrefix(prefix string) *UsersTable {
	return newUsersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UsersTable with assigned table suffix
func (a UsersTable) WithSuffix(suffix string) *UsersTable {
	return newUsersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUsersTable(schemaName, tableName, alias string) *UsersTable {
	return &UsersTable{
		usersTable: newUsersTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newUsersTableImpl("", "excluded", ""),
	}
}

func newUsersTableImpl(schemaName, tableName, alias string) usersTable {
	var (
		IDColumn          = postgres.IntegerColumn("id")
		FirstNameColumn   = postgres.StringColumn("first_name")
		LastNameColumn    = postgres.StringColumn("last_name")
		EmailColumn       = postgres.StringColumn("email")
		AddressColumn     = postgres.StringColumn("address")
		PhoneNumberColumn = postgres.StringColumn("phone_number")
		allColumns        = postgres.ColumnList{IDColumn, FirstNameColumn, LastNameColumn, EmailColumn, AddressColumn, PhoneNumberColumn}
		mutableColumns    = postgres.ColumnList{FirstNameColumn, LastNameColumn, EmailColumn, AddressColumn, PhoneNumberColumn}
	)

	return usersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		FirstName:   FirstNameColumn,
		LastName:    LastNameColumn,
		Email:       EmailColumn,
		Address:     AddressColumn,
		PhoneNumber: PhoneNumberColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
