//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type Creations struct {
	ID               uuid.UUID `sql:"primary_key"`
	Name             *string
	CreatorID        *uuid.UUID
	InstructionsLink *string
	ImageID          *uuid.UUID
	Price            *float64
}
